In [10]:
library(dplyr)

In [11]:
setwd("C:/Users/yerin")

In [12]:
file_path <- "data/global_air_quality_dataset.csv"

if(file.exists(file_path)) {
  air_quality <- read.csv(file_path)
  head(air_quality)
} else {
  print("Can't fined the file. Please check the path.")
}

  Date       City        Country AQI PM2.5..µg.m.. PM10..µg.m.. NO2..ppb.
1 2024-01-01 New York    USA      38 120.0         182.9        24.3
2 2024-01-01 Los Angeles USA     280  38.4          46.9        41.8
3 2024-01-01 London      UK      117 168.1          34.3        81.5
4 2024-01-01 Beijing     China   197  96.8          35.4        18.5
5 2024-01-01 Delhi       India   187  76.2         226.8        46.9
6 2024-01-01 Paris       France  170 217.6         278.0        21.7
  SO2..ppb. CO..ppm. O3..ppb. Temperature...C. Humidity.... Wind.Speed..m.s.
1 26.0      9.10     153.3    18.6             40           13.2
2 34.7      3.78     190.7    -2.2             59            9.5
3  8.2      3.67     105.4    36.3             62            3.4
4 39.4      9.51      92.8    29.9             32            1.8
5 17.2      1.02      68.4     9.9             55            3.3
6 45.2      1.77     125.2    37.4             67            1.4

In [13]:
summary(air_quality)

     Date               City             Country               AQI
 Length:3660        Length:3660        Length:3660        Min.   : 30.0
 Class :character   Class :character   Class :character   1st Qu.: 96.0
 Mode  :character   Mode  :character   Mode  :character   Median :165.0
                                                          Mean   :164.6
                                                          3rd Qu.:233.0
                                                          Max.   :300.0
 PM2.5..µg.m..    PM10..µg.m..     NO2..ppb.        SO2..ppb.
 Min.   :  5.1   Min.   : 10.0   Min.   :  5.10   Min.   : 2.00
 1st Qu.: 63.7   1st Qu.: 82.2   1st Qu.: 29.18   1st Qu.:13.70
 Median :125.8   Median :152.6   Median : 52.80   Median :26.20
 Mean   :126.4   Mean   :154.8   Mean   : 52.96   Mean   :25.94
 3rd Qu.:187.0   3rd Qu.:227.6   3rd Qu.: 76.70   3rd Qu.:38.20
 Max.   :250.0   Max.   :300.0   Max.   :100.00   Max.   :50.00
    CO..ppm.        O3..ppb.     Temperature...C.   Humidity....
 Min.   :0.100   Min.   : 10.1   Min.   :-10.000   Min.   :10.00
 1st Qu.:2.590   1st Qu.: 57.9   1st Qu.:  2.175   1st Qu.:31.00
 Median :4.910   Median :105.8   Median : 15.000   Median :51.00
 Mean   :5.024   Mean   :105.3   Mean   : 15.062   Mean   :50.66
 3rd Qu.:7.560   3rd Qu.:152.9   3rd Qu.: 27.525   3rd Qu.:71.00
 Max.   :9.990   Max.   :200.0   Max.   : 40.000   Max.   :90.00
 Wind.Speed..m.s.
 Min.   : 0.500
 1st Qu.: 4.100
 Median : 7.800
 Mean   : 7.789
 3rd Qu.:11.500
 Max.   :15.000

In [14]:
str(air_quality)

'data.frame':	3660 obs. of  13 variables:
 $ Date            : chr  "2024-01-01" "2024-01-01" "2024-01-01" "2024-01-01" ...
 $ City            : chr  "New York" "Los Angeles" "London" "Beijing" ...
 $ Country         : chr  "USA" "USA" "UK" "China" ...
 $ AQI             : int  38 280 117 197 187 170 177 164 123 241 ...
 $ PM2.5..µg.m..   : num  120 38.4 168.1 96.8 76.2 ...
 $ PM10..µg.m..    : num  182.9 46.9 34.3 35.4 226.8 ...
 $ NO2..ppb.       : num  24.3 41.8 81.5 18.5 46.9 21.7 9.5 26.1 6.4 74.4 ...
 $ SO2..ppb.       : num  26 34.7 8.2 39.4 17.2 45.2 46 18.4 19.7 16.4 ...
 $ CO..ppm.        : num  9.1 3.78 3.67 9.51 1.02 1.77 3.75 5.48 1.08 1.25 ...
 $ O3..ppb.        : num  153.3 190.7 105.4 92.8 68.4 ...
 $ Temperature...C.: num  18.6 -2.2 36.3 29.9 9.9 37.4 15.5 -6.8 7.1 37.5 ...
 $ Humidity....    : int  40 59 62 32 55 67 43 81 10 23 ...
 $ Wind.Speed..m.s.: num  13.2 9.5 3.4 1.8 3.3 1.4 1.8 14.3 5.3 14 ...

In [15]:
#Data cleaning
colnames(air_quality) <- c(
  "Date",
  "City",
  "Country",
  "AQI",
  "PM2.5",
  "PM10",
  "NO2",
  "SO2",
  "CO",
  "O3",
  "Temperature",
  "Humidity",
  "WindSpeed"
)

print("Missing values per column:")
print(colSums(is.na(air_quality)))

air_quality$Date <- as.Date(air_quality$Date)

[1] "Missing values per column:"
       Date        City     Country         AQI       PM2.5        PM10
          0           0           0           0           0           0
        NO2         SO2          CO          O3 Temperature    Humidity
          0           0           0           0           0           0
  WindSpeed
          0

In [16]:
air_quality_clean <- air_quality 
head(air_quality_clean)

  Date       City        Country AQI PM2.5 PM10  NO2  SO2  CO   O3
1 2024-01-01 New York    USA      38 120.0 182.9 24.3 26.0 9.10 153.3
2 2024-01-01 Los Angeles USA     280  38.4  46.9 41.8 34.7 3.78 190.7
3 2024-01-01 London      UK      117 168.1  34.3 81.5  8.2 3.67 105.4
4 2024-01-01 Beijing     China   197  96.8  35.4 18.5 39.4 9.51  92.8
5 2024-01-01 Delhi       India   187  76.2 226.8 46.9 17.2 1.02  68.4
6 2024-01-01 Paris       France  170 217.6 278.0 21.7 45.2 1.77 125.2
  Temperature Humidity WindSpeed
1 18.6        40       13.2
2 -2.2        59        9.5
3 36.3        62        3.4
4 29.9        32        1.8
5  9.9        55        3.3
6 37.4        67        1.4

In [22]:
#correlation between PM2.5 and other numerical variables
num_vars <- c(
  "PM2.5",
  "NO2",
  "O3",
  "CO",
  "SO2",
  "Temperature",
  "Humidity",
  "WindSpeed",
  "PM10"
)

cor <- cor(air_quality_clean[, num_vars]) 
cor_PM25 <- cor["PM2.5", ]

cor_PM25

       PM2.5          NO2           O3           CO          SO2  Temperature
 1.000000000  0.003930754  0.020700673 -0.027687004 -0.018380623  0.008992957
    Humidity    WindSpeed         PM10
-0.007076149  0.013813464  0.028090209

In [17]:
pollutants=c("NO2", "O3", "CO", "SO2")

results <- list()
counter <- 1

for (i in 1:length(pollutants)) {
  combos=combn(pollutants, i, simplify=FALSE)
  for (comp in combos) {
    formula_str=paste("PM2.5 ~", paste(comp, collapse = " + "))
    model=lm(as.formula(formula_str), data = air_quality_clean)
    
    results[[counter]]=data.frame(
      Combination = paste(comp, collapse = " + "),
      Adj_R2=summary(model)$adj.r.squared
    )
    counter=counter + 1
  }
}

adj_R2 <- do.call(rbind, results)
adj_R2 <- adj_R2[order(-adj_R2$Adj_R2), ]
print(adj_R2)

           Combination        Adj_R2
14       O3 + CO + SO2  6.835441e-04
8              O3 + CO  6.335724e-04
10            CO + SO2  5.431747e-04
3                   CO  4.934063e-04
15 NO2 + O3 + CO + SO2  4.292673e-04
11       NO2 + O3 + CO  3.815869e-04
13      NO2 + CO + SO2  2.880963e-04
6             NO2 + CO  2.405706e-04
9             O3 + SO2  2.198919e-04
2                   O3  1.552616e-04
4                  SO2  6.456622e-05
12      NO2 + O3 + SO2 -3.922092e-05
5             NO2 + O3 -1.018562e-04
7            NO2 + SO2 -1.952953e-04
1                  NO2 -2.579184e-04

In [18]:
model <- lm(PM2.5 ~ O3 + CO + SO2, data=air_quality_clean)
summary(model)

Call:
lm(formula = PM2.5 ~ O3 + CO + SO2, data = air_quality_clean)

Residuals:
     Min       1Q   Median       3Q      Max
-125.759  -61.949   -1.044   61.251  129.253

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept) 129.37801    3.92661  32.949   <2e-16 ***
O3            0.02624    0.02133   1.230    0.219
CO           -0.67600    0.41165  -1.642    0.101
SO2          -0.09117    0.08383  -1.088    0.277
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 70.99 on 3656 degrees of freedom
Multiple R-squared:  0.001503,	Adjusted R-squared:  0.0006835
F-statistic: 1.834 on 3 and 3656 DF,  p-value: 0.1387